//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimaAV.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnteEspecialidad
    {
        public System.Guid ORID { get; set; }
        public System.Guid IdEnte { get; set; }
        public System.Guid IdEspecialidad { get; set; }
    
        public virtual Ente Ente { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
